/**
 * Centralized Icon Registry
 * All Unicons from @iconscout/react-unicons used across E-guriro.
 * Import from here  never import directly from the package in pages.
 */
export {
  UilShoppingCart,
  UilSearch,
  UilUser,
  UilUserPlus,
  UilSignInAlt,
  UilSignOutAlt,
  UilHeart,
  UilHeartAlt,
  UilStar,
  UilTruck,
  UilPackage,
  UilStore,
  UilShield,
  UilBars,
  UilTimes,
  UilTimesCircle,
  UilCheck,
  UilCheckCircle,
  UilExclamationTriangle,
  UilInfoCircle,
  UilArrowRight,
  UilArrowLeft,
  UilArrowUp,
  UilArrowDown,
  UilAngleDown,
  UilAngleUp,
  UilAngleRight,
  UilMobileAndroid,
  UilCreditCard,
  UilMoneyBill,
  UilChart,
  UilChartBar,
  UilComment,
  UilCommentAlt,
  UilMessage,
  UilPlane,
  UilEnvelopeSend,
  UilMapMarker,
  UilPhone,
  UilEnvelope,
  UilEdit,
  UilTrashAlt,
  UilPlus,
  UilMinus,
  UilFilter,
  UilImage,
  UilBell,
  UilEye,
  UilLock,
  UilUnlock,
  UilTag,
  UilSlidersV,
  UilHome,
  UilGrid,
  UilListUl,
  UilRefresh,
  UilCopy,
  UilShare,
  UilUpload,
  UilFire,
  UilClock,
  UilAward,
  UilShieldCheck,
  UilHeadphones,
  /* Electronics Category Icons */
  UilTablet,
  UilLaptop,
  UilCamera,
  UilPlug,
  UilWifi,
  UilBolt,
  UilWatch,
  UilHistory,
  UilDesktop,
  UilMonitor,
  UilKeyboard,
  UilMicrophone,
  UilVideo,
  UilTvRetro,
  UilPower,
  UilBatteryBolt,
  /* Product detail icons */
  UilCornerUpLeft,
  /* Admin panel icons */
  UilCog,
  UilGlobe,
  UilImages,
  /* Chat UI icons */
  UilEllipsisV,
  UilSmile,
  UilUserCircle,
} from '@iconscout/react-unicons';
